build: "off"

environment:
  matrix:
    - PYTHON_VERSION: "3.6"
      MINICONDA: C:\Miniconda36-x64
    - PYTHON_VERSION: "3.7"
      MINICONDA: C:\Miniconda3-x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy scikit-learn numba nose"
  - activate test-environment
  - pip install -e .

test_script:
  - nosetests
  